# Setup
title:        TensorFlow Studio
tagline:      A Python model management framework to simplify and expedite your model building experience.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       TensorFlow Studio
  url:        https://github.com/ilblackdragon/studio

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
