# Setup
title:        TensorFlow Studio
tagline:      A Python model management framework to simplify and expedite your model building experience.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Tensorflow Studio
  url:        http://tfstudio.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
